### ISSUE TITLE
Store extra metadata in attributes

### ISSUE THREAD

**Issue by cparcerisas** [mbari-org/pbp#48]
If I am not mistaken, at the moment the netcdf files do not store the information regarding: 

- original sampling frequency 
- sensitivity used for the calculation 

Do you think it would be useful to add these? For us it would, especially the original sampling frequency. 

Thanks!

**Comment by ryjombari** [comment]
@cparcerisas 
Original sampling frequency was not included in the SoundCoop standard, but I agree that it is useful metadata.
Sensitivity is stored in the netCDF output, as the variable named... sensitivity.  :)

**Comment by carueda** [comment]
@ryjombari @cparcerisas @danellecline 

If not (yet) in the "standard", we could enable it via some optional flag? And how would it look like, maybe (just using yaml for illustration) like this?

```yaml
original_sampling_frequency:
  standard_name: sound_frequency
  long_name: Original sampling frequency
  units: Hz
  coverage_content_type: qualityInformation
```
